# filename: mise.toml
# description: Configuration file for Mise, a task runner for Swift projects
# creation_date: 2024-05-05
# update_date: 2024-05-05
# documentation:

[env]
APP_VERSION = "development"
ENV_NAME = "development"
IRC_CHANNEL_GIT = "#dev"
IRC_CHANNEL_SEEDBOX = "#dev"
IRC_CHANNEL_SYSOPS = "#dev"
IRC_HOST = "localhost" # Replace with your IRC server's IP address
IRC_NICK = "dev_cloe"
SENTRY_DSN = "" # Replace with your Sentry DSN if you have one
SWAGGER_ENABLED = "true"

[tasks.help]
description = "List available project tasks"
run = "mise tasks ls"

[tasks.setup_precommit]
description = "Setup pre-commit hooks"
run = "pre-commit install"

[tasks.precommit]
depends = ["setup_precommit"]
description = "Run pre-commit hooks on all files"
run = "pre-commit run --all-files"

[tasks.test]
depends = ["setup_precommit"]
description = "Run unit tests"
run = "cd src && swift test"

[tasks.image_build]
description = "Build Docker/Podman image"
run = "if command -v docker >/dev/null 2>&1; then docker build -t $(basename $(pwd)):dev -f docker/Dockerfile .; elif command -v podman >/dev/null 2>&1; then podman build -t $(basename $(pwd)):dev -f docker/Dockerfile .; else echo 'Neither Docker nor Podman is installed.'; fi"

[tasks.dev]
description = "Run development environment"
run = "cd src && swift run"
